name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        name:
          - trilby
        edition:
          - workstation
          - server
        channel:
          - unstable
          - 22_11
        hostArch:
          - x86_64
        format:
          - isoImage
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}-${{ matrix.edition }}-${{ matrix.channel }}-${{ matrix.hostArch }}-${{ matrix.format }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: trilby
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: |
        nix build \
          --accept-flake-config \
          --print-build-logs \
          .#${{ matrix.name }}-${{ matrix.edition }}-${{ matrix.channel }}-${{ matrix.hostArch }}-${{ matrix.format }}
