name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Nix build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v24
    - uses: ryanccn/attic-action@v0
      with:
        endpoint: https://cache.ners.ch
        cache: trilby
        token: ${{ secrets.ATTIC_TOKEN }}
    - name: Build
      run: |
        nix build .#allConfigs \
          --accept-flake-config \
          --print-build-logs
