name: Continuous integration
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch: # allows manual triggering
env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 0

jobs:
  build:
    strategy:
      matrix:
        edition: ['workstation', 'server']
        release: ['unstable', '22.11']
        hostArch: ['x86_64']
        format: ['isoImage']
    runs-on: 'ubuntu-latest'
    name: trilby-${{ matrix.edition }}-${{ matrix.release }}-${{ matrix.hostArch }}-${{ matrix.format }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
    - uses: cachix/cachix-action@v12
      with:
        name: trilby
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: |
        nix build \
          --accept-flake-config \
          --print-build-logs \
          ".#trilby-${{ matrix.edition }}-${{ matrix.release }}-${{ matrix.hostArch }}-${{ matrix.format }}"
